// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Fri May 13 01:43:07 2022

ci7486 ci7486_inst
(
	.A1(A1_sig) ,	// input  A1_sig
	.A2(A2_sig) ,	// input  A2_sig
	.A3(A3_sig) ,	// input  A3_sig
	.A4(A4_sig) ,	// input  A4_sig
	.B1(B1_sig) ,	// input  B1_sig
	.B2(B2_sig) ,	// input  B2_sig
	.B3(B3_sig) ,	// input  B3_sig
	.B4(B4_sig) ,	// input  B4_sig
	.Y1(Y1_sig) ,	// output  Y1_sig
	.Y2(Y2_sig) ,	// output  Y2_sig
	.Y3(Y3_sig) ,	// output  Y3_sig
	.Y4(Y4_sig) 	// output  Y4_sig
);

